version: "3"
services:
  inexchg-angular-app:
    build: .
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl_certificate/alwrite.com.chained.crt:/etc/nginx/conf.d/alwrite.com.chained.crt:ro
      - ./nginx/ssl_certificate/alwrite.com.key:/etc/nginx/conf.d/alwrite.com.key:ro